module.exports = {
    CHAT: "CHAT",
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    CHECK_USER: "CHECK_USER",
    LOGOUT: "LOGOUT",
    USERS_ONLINE: "USERS_ONLINE",
};
